{
 "title": "Market Screen",
 "tags": [ "finance" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "sector",
    "label": "Sector",
    "query": "select distinct(sector) from stocks;"
   },
   {
    "name": "industry",
    "label": "Industry ",
    "query": "select distinct(industry) from stocks;"
   },
   { "name": "rsi_rating_f", "label": "RSI Rating - Max", "query": "50" },
   { "name": "sma_rating_f", "label": "SMA Rating - Max", "query": "1,2,3,4,5" },
   { "name": "macd_rating_f", "label": "MACD Rating - Max", "query": "1,2,3,4,5" }
  ]
 },
 "panels": [
  { "title": "Watch List", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  { "title": "Watch List", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 23, "x": 0, "y": 1 } },
  {
   "title": "Industry Screen",
   "type": "table",
   "gridPos": { "h": 27, "w": 8, "x": 0, "y": 6 },
   "targets": [
    {
     "rawSql": "select avg(rsi_rating) as \"RSI\", avg(sma_rating) as \"SMA\", sector as \"Sector\", industry as \"Industry\"\nfrom stocks \nwhere industry IN ($industry) AND sector IN ($sector)\ngroup by sector, industry\norder by \"RSI\" desc, \"SMA\" asc; ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Ticker Screener",
   "type": "table",
   "gridPos": { "h": 15, "w": 15, "x": 8, "y": 6 },
   "targets": [
    {
     "rawSql": "select rsi_rating as \"RSI\", sma_rating as \"SMA\", macd_rating as \"MACD\", ticker, name, sector, industry, beta, dividend_yield, pe\nfrom stocks\nwhere rsi_rating <= $rsi_rating_f \nAND sma_rating <= $sma_rating_f \nAND macd_rating <= $macd_rating_f \nAND industry \nIN ($industry) AND sector IN ($sector)\norder by rsi_rating, sma_rating, macd_rating asc; ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  {
   "title": "Ticker - Watchlist",
   "type": "table",
   "gridPos": { "h": 12, "w": 15, "x": 8, "y": 21 },
   "targets": [
    {
     "rawSql": "select rsi_rating as \"RSI\", sma_rating as \"SMA\", macd_rating as \"MACD\", watchlist.ticker, name, sector, industry, beta, dividend_yield, pe\nfrom stocks, watchlist\nwhere stocks.ticker = watchlist.ticker\norder by rsi_rating, sma_rating, macd_rating asc; ",
     "source": "url",
     "type": "json",
     "url": "https://github.com/yesoreyeram/grafana-infinity-datasource/blob/main/testdata/users.json",
     "url_options": { "data": "", "method": "GET" }
    }
   ]
  },
  { "title": "Analytics", "type": "volkovlabs-form-panel", "gridPos": { "h": 5, "w": 23, "x": 0, "y": 33 } }
 ]
}